spring:
  application:
    name: auth-server #服务名称

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ts_bdth?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true
    # 邮箱
  mail:
    host: smtp.qq.com
    username: 你的邮箱
    password: '邮箱授权码'
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    port: 587

# 支付宝配置
ali-pay:
  # 支付宝应用ID
  appId: '你的支付宝应用ID'
  # 支付宝公钥
  alipayPublicKey: ''
  # 私钥
  privateKey: ''
  # 后端域名
  domain: 'https://718363a8x8.zicp.fun'



server: #端口号
  port: 9008

thread:
  pool:
    enable: true

mybatis-plus:
  typeAliasesPackage: com.cn.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
