spring:
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/ts_bdth?useUnicode=true&tinyInt1isBit=false&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
  application:
    name: chat-server 

server:
  port: 9003
   
mybatis-plus:
  typeAliasesPackage: com.cn.entity
  configuration:
   # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'

