spring:
  codec:
    max-in-memory-size: 1048576
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  application:
    name: drawing-server #服务名称

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ts_bdth?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true

server: #端口号
  port: 15351


config:
  sd:
    # sd请求连接 格式  http://XXXXXXX/sdapi/v1/
    requestUrl: ''
    # 模型列表
    model-list:
      - modelName: 'SHMILY_v1.0.safetensors'
        modelText: '水彩模型'

      - modelName: 'AWPortrait_v1.2.safetensors'
        modelText: '海报杂志_AWPortrait'

      - modelName: 'revAnimated_v1.2.2.safetensors'
        modelText: '动漫_RevAnimated'
    # 采样方法
    sampler-list: [ 'Euler a','Euler','LMS','Heun','DPM2','DPM2 a' ]
    # 迭代步数
    steps:
      min: 10
      max: 30

  # 绘图POOL
  pool:
    # 每个用户可创建的任务数量
    maximum-task: 3
    # sd可并行处理任务数( 未实装, 因为SD的实时出图仅限单任务,如果修改 请修改sd部分业务代码,本项目只做单SD )
    sd-concurrent: 1
    # dall可并行处理任务数
    dall-concurrent: 5

# 百度翻译 可选接入
baidu-translation:
  appid: '百度翻译APPID'
  secret: '百度翻译密钥'

# 不可修改 关闭会导致绘图问题
thread:
  pool:
    enable: true


mybatis-plus:
  typeAliasesPackage: com.cn.entity
  configuration:
   # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
