spring:
  cloud:
    gateway:
      httpclient:
        websocket:
          max-frame-payload-length: 10485760
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              # 你的前端域名
              - "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: ts-auth
          uri: lb://auth-server
          predicates:
            - Path=/auth-api/**
          filters:
            - StripPrefix=1

        - id: ts-chat
          uri: lb://chat-server
          predicates:
            - Path=/chat-api/**
          filters:
            - StripPrefix=1

        - id: ts-drawing
          uri: lb://drawing-server
          predicates:
            - Path=/drawing-api/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: initialCapacity=500,expireAfterWrite=5s
  application:
    name: gateway-server

server:
  #   SSL证书
  ssl:
    key-store: classpath:anchwngb.cn.pfx
    key-store-password: fy981l4601q
    key-store-type: PKCS12
  port: 9000

