spring:
  data:
    redis:
      timeout: 10s
      database: 0  
      host: 127.0.0.1   
      #如果没有设置为 ''
      password: 123
      port: 6379  
      lettuce:
        pool:
          max-active: 200 
          max-wait: -1ms 
          max-idle: 10  
          min-idle: 0 